spring:
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes: 172.16.10.212:6379,172.16.10.212:6380,172.16.10.212:6381
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 30
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5000
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 1
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: false